network:
    version: 2
    renderer: networkd
    ethernets:
        enp3s0:
            addresses:
                - 192.168.1.201
            nameservers:
                 addresses: [8.8.8.8, 8.8.4.4]
        